# Generated by Django 4.1.3 on 2022-12-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('sname', models.CharField(max_length=64)),
                ('sfees', models.FloatField()),
                ('saddr', models.CharField(max_length=100)),
            ],
        ),
    ]
